name: E2E Tests (Cypress)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # Start your dev server
      - name: Start app
        run: npm run dev &

      - name: Wait for app to boot
        run: sleep 30s
        shell: bash

    #   # Run Cypress
    #   - name: Run Cypress tests
    #     run: npm run cypress:run

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress tests (Electron)
        # env:
        #   NODE_OPTIONS: --import tsx
        run:  unset NODE_OPTIONS && npx cypress run --browser chrome

